getwd()
setwd("Documents/2016120036_STC/")
dataset <- read.csv("rainfall_dataset.csv", stringsAsFactors = FALSE)
View(dataset)

#EDA
summary(dataset)
#Remove rows containing na
sum(is.na(dataset))
nrow(dataset)
clean.dataset <- na.omit(dataset)
sum(is.na(clean.dataset))
library(dplyr)
andaman.data <- subset(clean.dataset, clean.dataset$SUBDIVISION == "ANDAMAN & NICOBAR ISLANDS")
View(andaman.data)
barplot(height = andaman.data$total ,xlab = andaman.data$YEAR, ylab = andaman.data$total)
nrow(andaman.data)
##Create model
f <- total ~ (YEAR)
library(caret)
install.packages("caTools")
library(caTools)
split <- sample.split(andaman.data, SplitRatio = 0.8, group = NULL)
train.andaman <- subset(andaman.data , split == TRUE)
nrow(train.andaman)
test.andaman <- subset(andaman.data, split == FALSE)
nrow(test.andaman)
linear.model <- lm(formula = f, data = train.andaman)
predictor <- predict(linear.model,newdata = test.andaman)
summary(predictor)
predictor
summary(linear.model)
